trigger:
  branches:
    exclude:
    - main
    - next
    - test
  paths:
    exclude:
    - deploy/*

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'

steps:
  # Install Node.js
  - task: UseNode@1
    inputs:
      version: $(nodeVersion)
    displayName: 'Install Node.js'

  # Install dependencies
  - script: |
      npm install -g @angular/cli
      npm ci
    displayName: 'Install dependencies'

  # Build the project
  - script: |
      ng build ngx-sp-infra --configuration=production
    displayName: 'Build project'
  
  # Run tests
  - script: |
      ng test ngx-sp-infra --watch=false --code-coverage --browsers=ChromeHeadless
    displayName: 'Run tests'
