trigger:
  branches:
    include:
    - main
    - next
    - test
    - azure-pipelines
  paths:
    exclude:
    - deploy/*

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'

jobs:
  - job: 'Build'
    steps:
      # Faz Checkout do repositório
      - checkout: self
      
      # Desabilita o shallow fetch
        fetchDepth: 0


      # Step 1: Define as variáveis que serão usadas no restante do flow
      - script: |
          PROJECT=$(jq -r '.project' deploy/release-info.json)
          VERSION=$(jq -r '.version' deploy/release-info.json)
          NOTES=$(jq -r '.notes' deploy/release-info.json)
          TAG=$(jq -r '.tag' deploy/release-info.json)
          package_version=$(jq -r ".version" package.json)
          echo "##vso[task.setvariable variable=PackageVersion;isOutput=true]$package_version"
          echo "##vso[task.setvariable variable=ProjectName;isOutput=true]$PROJECT"
          echo "##vso[task.setvariable variable=ProjectVersion;isOutput=true]$VERSION"
          echo "##vso[task.setvariable variable=PublishNotes;isOutput=true]$NOTES"
          echo "##vso[task.setvariable variable=ProjectTag;isOutput=true]$TAG"
        displayName: 'Define variáveis com base no arquivo de release'
        name: buildStep

      # Step 2: Teste as variáveis
      - script: |
          echo "Package Version: $(buildStep.PackageVersion)"
          echo "Project Name: $(buildStep.ProjectName)"
          echo "Project Version: $(buildStep.ProjectVersion)"
          echo "Publish Notes: $(buildStep.PublishNotes)"
          echo "Project Tag: $(buildStep.ProjectTag)"
        displayName: 'Mostrar informações de release'
      
      - script: |
          echo "Full branch reference: $(Build.SourceBranch)"
          echo "Short branch name: $(Build.SourceBranchName)"
        displayName: 'Lê o nome da branch'

      # Instalar o Node.js
      - task: UseNode@1
        inputs:
          version: $(nodeVersion)
        displayName: 'Instalar o Node.js'

      # Instalar dependências gerais
      - script: |
          npm install -g @angular/cli
          npm ci
        displayName: 'Instalar dependências gerais'

      # Builda e executa testes unitários com cobertura
      - script: |
          if [ "$(buildStep.ProjectName)" == "ngx-sp-auth" ]; then
            cd projects/ngx-sp-auth
            npm ci
            cd ../../
          fi

          npm run build:$(buildStep.ProjectName):prod
        displayName: 'Buildar e executar testes'
      

      - task: npmAuthenticate@0
        displayName: 'Authenticate to Azure Artifacts feed'
        inputs:
          workingFile: projects/$(buildStep.ProjectName)/.npmrc
          feedUrl: 'https://pkgs.dev.azure.com/SisproERP/_packaging/InfraCodeLibs/npm/registry/'

      - script: |
          cp projects/$(buildStep.ProjectName)/.npmrc dist/$(buildStep.ProjectName)/.npmrc
        displayName: 'Copiar arquivo .npmrc para a dist'
      
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'dist/$(buildStep.ProjectName)'
          verbose: true
          customCommand: 'npm publish --tag next'
          publishRegistry: 'useFeed'
          publishFeed: '3867b2a2-a6b0-4e97-87fc-c757aab71b59/ca9c05c8-bdc6-420e-91a8-dfac69d79b82'
        displayName: 'Publicar pacote'

      # - script: |
      #     cp projects/$(buildStep.ProjectName)/.npmrc dist/$(buildStep.ProjectName)/.npmrc
      #     cd dist/$(buildStep.ProjectName)/
      #     npm publish --registry=https://pkgs.dev.azure.com/SisproERP/PeD/_packaging/npm_packages/npm/registry/ --userconfig=projects/$(buildStep.ProjectName)/.npmrc
      #   displayName: Publish to Azure Artifacts

