name: CI

run-name: CI

on:
  push:
    branches:
      - main
      - next
      - test
      - next-workflow

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
        
      - name: Instalar dependências
        run: npm install
        
      - name: Executar testes
        run: npm run test:headless
