name: CI/CD Pipeline
run-name: CI/CD

on:
  push:
    branches:
      - next-workflow

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm run test:headless

  cd-job:
    runs-on: ubuntu-latest
    needs: ci-job  # Garante que o job de CD só execute após o CI
    if: ${{ success() }}  # Executa apenas se o job anterior for bem-sucedido
    steps:
      - run: echo 'Deploy iniciado após o CI'
