name: CI/CD

on:
  push:
    branches:
      - package

jobs:
  deploy-package:    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Garante que todo o histórico de commits seja trazido

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Install dependencies
      run: npm install

    - name: Build the library and add tags
      run: npm run build ngx-sp-infra

    - name: Get the version tag
      run: |
        TAG=$(node scripts/tag.js)
        echo "Tag encontrada: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Publish to GitHub Packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE }}
      run: |
        cd dist/ngx-sp-infra
        
        if [ "${{ github.ref }}" == "refs/heads/package" ]; then
          npm publish --tag latest
        fi
