name: PLACEHOLDER

on:
  workflow_dispatch:
    inputs: 
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'CI'
      
      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'S0lturn3'
      
      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'infra-code-libs'

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
